### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by raitheon** [benjefferies/raiblockpayments#2]
```
root@localhost:~/raiblockpayments-master# python run.py "[::1]" "xrb_1niabkx3gbxit5j5yyqcpas71dkffggbr6zpd3heui8rpoocm5xqbdwq44oh"
  File "run.py", line 18
    return requests.post(f'http://{host}:7076', json.dumps(data)).json().get('history', [])
                                             ^
SyntaxError: invalid syntax
```

**Comment by benjefferies** [comment]
If you run `python --version` what do you get? It's using [fstring](https://www.python.org/dev/peps/pep-0498/) which was introduced into python 3.6. This could be the reason you're seeing that invalid syntax. If it is I use https://github.com/pyenv/pyenv to manage my python versions. I think this is the easiest way to install it if you aren't using it https://github.com/pyenv/pyenv-installer.
